def FindP(text,length):
    dict ={}
    count=0
    for j,ele in enumerate(text):

        
        if text[j:j+length] in dict:
            
            dict[text[j:j+length]]+=1
            
        else:
            dict[text[j:j+length]]=0
    
    max_keys = [key for key, value in dict.items() if value == max(dict.values())]
    for ele in max_keys:
        print(ele,end=" ")
text = "GCACATGCGGGCACATGCGGAGGCACGGGCCTTTATGACGCACATGCGGCCTTTATGACGCACATGCGGAGGCCTTGGAGGCACGGGGCACATGCGGAGGCACGGGCCTTTATGACCCTTTATGACAGGCCTTGGAGGCACGGGCCTTTATGACGCACATGCGGCCTTTATGACCCTTTATGACCCTTTATGACCCTTTATGACAGGCACGGGACCCCATCGCACATGCGGCCTTTATGACCCTTTATGACGCACATGCGGCCTTTATGACACCCCATCCCTTTATGACAGGCACGGGGCACATGCGGAGGCCTTGGAGGCCTTGGGCACATGCGGCCTTTATGACAGGCACGGGACCCCATCCCTTTATGACACCCCATCCCTTTATGACGCACATGCGGAGGCCTTGGAGGCACGGGAGGCCTTGGAGGCACGGGACCCCATCACCCCATCACCCCATCCCTTTATGACGCACATGCGGGCACATGCGGAGGCCTTGGCCTTTATGACACCCCATCCCTTTATGACACCCCATCGCACATGCGGAGGCCTTGGCCTTTATGACAGGCACGGGAGGCCTTGGCCTTTATGACCCTTTATGACGCACATGCGGCCTTTATGACGCACATGCGGCCTTTATGACAGGCACGGGAGGCCTTGGCCTTTATGACACCCCATCGCACATGCGGAGGCACGGGAGGCACGGGCCTTTATGACGCACATGCGGAGGCCTTGGACCCCATCAGGCCTTGGAGGCCTTGGACCCCATCCCTTTATGACCCTTTATGACACCCCATCCCTTTATGACCCTTTATGACGCACATGCGGAGGCCTTGGGCACATGCGGCCTTTATGACGCACATGCGGGCACATGCGGACCCCATCACCCCATCACCCCATC"
FindP(text,14)