'''
As you will see in this exercise, some Rosalind problems will ask for a (very large) integer solution modulo a smaller number to avoid the computational pitfalls that arise with storing such large numbers.

Given: A protein string of length at most 1000 aa.

Return: The total number of different RNA strings from which the protein could have been translated, modulo 1,000,000. (Don't neglect the importance of the stop codon in protein translation.)


'''

codon_table  = '''UUU F      CUU L      AUU I      GUU V
UUC F      CUC L      AUC I      GUC V
UUA L      CUA L      AUA I      GUA V
UUG L      CUG L      AUG M      GUG V
UCU S      CCU P      ACU T      GCU A
UCC S      CCC P      ACC T      GCC A
UCA S      CCA P      ACA T      GCA A
UCG S      CCG P      ACG T      GCG A
UAU Y      CAU H      AAU N      GAU D
UAC Y      CAC H      AAC N      GAC D
UAA Stop   CAA Q      AAA K      GAA E
UAG Stop   CAG Q      AAG K      GAG E
UGU C      CGU R      AGU S      GGU G
UGC C      CGC R      AGC S      GGC G
UGA Stop   CGA R      AGA R      GGA G
UGG W      CGG R      AGG R      GGG G '''

table  = codon_table.split()
dict  = dict(zip(table[0::2],table[1::2]))


flipped = {}
for key,value in dict.items():
    if value not in flipped:
        flipped[value] = [key]
    else:
        flipped[value].append(key)

prot = "MGWDFMYPPAEFLFSAQYWMKWCGDINEEAGGLMWPTKGQQARDHNPQSNHPICAYTELTVIYLAQNSCDMALCGGAGNEAWVVDMERASQITKHLSRSWASIPLWAMYLHALGRDVCVELFWMWKFPMGNQWLEEDWIEWQHTFHKAYHTFDRYCFDNPALHFSDPLQDGKEKYVPNVYFTRNWNKQHGWKIDRNTTCINVFYSAMYMRTFQVGFEFDCRRYPIADHFYSSAHLPYDKYCVHESMVEFPSHCYYSEFAFLEYHANLANGLNGSCKIFQGGFPGFSTLFAFTLGYHDKKQTGMQYPPIVAITTYYLTFQDYVRGSIWTWCVVPENFQSRQLGMKTLMHICMESMKLRGFDKTEHNHFTTWHHGSSFEPYQGNRCSKEHEKDDVMLGKSNWVLLMLVMVGRDKIYYCAQRYYYPGDSCHLYWTLGWGCGLIYKCTGCAEVCHMMDCMMRNNTSVWPIPNMCTHYSMAKVKRCRTVDETPFLMQSDWTCCTQFFMQSSSTRDINFGDVECGDMYTIVGTFAWAQCEIFKMGRITCSCGMWTGKMWVFNKPVGGPHENCTIESWNRDWPFAFVWICPKMNWKYGYCMGFISYAFIWEPCWDEIFHMHGDVPWMSFYSWIHVIFYAFSFEEYYACDCDDCMGRNLWMYLRHNVGAREQLEMSPANMNYYIFLRHQCARRWFGTGAPGVPWRYEFCWYAMLFCQYINEMTVTSESIAPRTPARPLTHDNHLHQRIYHNRTDTPVDPYTPHFCDQQKIIHICMYPQCEQELTLAQIWTIRNQKRGWDSYGLRFRHRPNRGICHPAFGGVKYNRRHKAIMVMDLCWNAYWMPYYAACSRNDLAEILLLFYGQKCWVMSACFKNILKTGAIVIIVWEMEKVQWYGVNRHFKRWSSSLIQWACFLYMWQPYVCFCSSSPEFWIQDITVGEYLCGAVCFQMKQTDYSHDWTPDYYHIYRLFYSGVLELNCWANTIFSYKWHMQSCLQVCTYVTLLCRMFE"

mul = 3
for ele in prot:
    mul*=len(flipped[ele])

print(mul % 1000000)